<div><?php foreach ($this->maxBid as $value) { ?>
	<?php 
	if(isset($value))
	{
	echo "This Bid must be greater than $".$value;
	}
	 ?>
<script>
	$(function(){

    $('#SubmitYourBid').click(function(){

		if($('#amount').val() == '')
    	{
    		$('#amount').css({'border-color':'red'});
    		return false;
    	}
    	else if($('#amount').val() <= <?php echo $value; ?>)
    	{
    		alert("Your Bid must be greater than <?php echo '$'.$value; ?>");
    		return false;
    	}
    	
    });

});
</script>
<?php }?></div>
<?php echo $this->form; ?>





