
<div class="clear"> 

<h3>Please Make your Bid </h3> </div>



<div id="categories">                                               <!--categories-->

<ul>

<?php foreach ($this->items as $item): ?>
 <li><a href=<?php echo $this->url(array(
		'controller'=>'items',
		'action'=>'list',
		'cat'=> $item['CategoryName'])); ?> ><?php echo  $item['CategoryName']?></a></li>

  <?php endforeach; ?>

</ul>

</div>
 
<div id="product">             <!--product-->

<div class="productimg">

</div>



<div class="productviews">

<ul>

<li></li>

<li></li>

</ul>

</div>



<div class="productdesc">

<!-- <h15>Product Name</h15> -->


<!-- <a href="#"><div class="star">

</div></a> -->

<h17><div><?php foreach ($this->maxBid as $value) { ?>
 <?php 
 if(isset($value))
 {
 echo "This Bid must be greater than $".$value;
 }
  ?>
<script>
 $(function(){

    $('#SubmitYourBid').click(function(){

  if($('#amount').val() == '')
     {
      $('#amount').css({'border-color':'red'});
      return false;
     }
     else if($('#amount').val() <= <?php echo $value; ?>)
     {
      alert("Your Bid must be greater than <?php echo '$'.$value; ?>");
      return false;
     }
     
    });

});
</script>
<?php }?></div>
<?php echo $this->form; ?></h17>



</div>



</div>



<div id="featured_slider">						<!--featured-->

<h22>Related Products</h22>



<div id="arrow" class="arrowl">

</div>



<div id="fslider">

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Watches</span></div>

<div class="ftext1">Price:<span> 5$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span>  Watches</span></div>

<div class="ftext1">Price:<span> 10$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span>  Watches</span></div>

<div class="ftext1">Price:<span> 70$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span>  Watches</span></div>

<div class="ftext1">Price:<span> 59.7$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span>  Watches</span></div>

<div class="ftext1">Price:<span> 15$</span></div>

</div>



</div>

<div id="arrow" class="arrowr">

</div>





</div>



<div class="social">

<h8>Share This Link: <a href="#">www.abcdefg.com/home</a></h8>

</div>