
<div id="footer">                                                           <!--footer-->

	<div id="social">                                                           <!--social icons-->

		<h9>Stay Connected</h9>

			<div class="icon">


				<a href="#" id="social" class="facebook"></a>
				<a href="#" id="social" class="twitter"></a>

				<a href="#" id="social" class="pintrest"></a>

				<a href="#" id="social" class="email"></a>

			</div>

	</div>      





	<div id="fcol2">

		<h9>City</h9>

	<ul>

		<li><a href="#">Atlanta</a></li>

		<li><a href="#">Austin</a></li>

		<li><a href="#">Baltimore</a></li>

		<li><a href="#">Boston</a></li>

		<li><a href="#">Chicago</a></li>

		<li><a href="#">Washington, DC</a></li>

		<li><a href="#">More...</a></li>

	</ul>

</div>



	<div id="fcol3">

			<h9>Category</h9>

		<ul>

			<li><a href="#">Cars</a></li>

			<li><a href="#">Bikes </a></li>

			<li><a href="#">Phones</a></li>

			<li><a href="#">Laptops </a></li>

			<li><a href="#">Animals</a></li>

			<li><a href="#">Frozen food</a></li>

			<li><a href="#">More...</a></li>

		</ul>

	</div>



<div id="fcol4">

<h9>Properties</h9>

<ul>

<li><a href="#">Huge Land(narvana)</a></li>

<li><a href="#">Size</a></li>

<li><a href="#">Weight</a></li>

<li><a href="#">Color</a></li>

<li><a href="#">Height</a></li>

<li><a href="#">Taste</a></li>

<li><a href="#">More...</a></li>

</ul>

</div>



<a href="#"><div class="flogo">

</div></a>



<div class="rights">

<p>All Rights Reserved <a href="#">i-Intellect.co</a></p>

</div>



</div>                                                                  <!--footer-->



</div>                                                      <!--container-->



</body>

</html>
