<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" type="text/css" href="/css/main.css" />

<title>Auction</title>

</head>



<body>



<div id="container">                                                <!--container-->



<div id="header">                                                   <!--header-->



<a href="#"><div class="logo">                                                  <!--Logo-->

</div></a>                                                              <!--Logo-->



<div class="fblike">                                                <!--Facebook Like-->

</div>                                                              <!--Facebook Like-->



<div class="menu">                                                  <!--Menu-->



<ul>

<li><a href="#">Post a Free Ad</a></li>

<li><a href="#">Community</a></li>
<?php if(!Zend_Auth::getInstance()->hasIdentity()): ?>
<li><a href="/user/sign-in">Sign in</a></li>
<li><a href="/user/register">Sign up</a></li>
<?php endif; ?>

<li><a href="#">Join Now</a></li>

<li><a href="#">Cart</a></li>
<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
<li><a href="/user/logout">logout</a></li>
<?php endif; ?>

</ul>



</div>                                                              <!--Menu-->



                                                              <!--search-->



</div>                                                              <!--header-->
