<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
<h2>Welcome to home</h2>
<?php endif; ?>

<div>
<?php 
     
?>   
</div>                                                      

<?php foreach ($this->pitemDetail as $piDetail): ?>
 		<?php echo $piDetail['title']; ?><br />
 		<?php echo $piDetail['condition']; ?><br />
 		<?php echo $piDetail['countries']; ?><br />
 		<?php echo $piDetail['subtitle']; ?><br />
 		<?php echo $piDetail['SaleType']; ?><br />
 		<?php echo $piDetail['PropertyType']; ?><br />
 		<?php echo $piDetail['ZipPostalCode']; ?><br />
 		<?php echo $piDetail['StateProvince']; ?><br />
 		<?php echo $piDetail['genre']; ?><br />
 		<?php echo $piDetail['desc']; ?><br />

<?php if($piDetail['auctionOrFixed'] == '0'): ?>
 	<a href='/bids/index/itemID/<?php echo $piDetail["id"];?>'>Bid Now</a>
<?php endif; ?>

<?php if($piDetail['auctionOrFixed'] == '1'): ?>

	<?php $itemid = $this->pitemDetail['id'];?>

		<?php if(isset($_SESSION['cart'])): ?>

	            		<?php $key = array_search($itemid, $_SESSION['cart']); // $key = 2;?>

<!-- 						<?php if($key!= null):?>
					  	<a id="addToCart" href="<?php echo $this->Url(
					                            array(
					                            'controller' =>  'items',
					                            'action'     =>  'addtocart',
					                            'id'         =>   $piDetail['id'],
					                            )); ?>">Add to Cart</a>
					    <?php endif; ?> -->

						<?php if($key==null):?>
							<a>Item already added to your cart</a>
							<?php endif; ?>
	                    
	    <?php endif; ?>

       <?php if(!isset($_SESSION['cart'])): ?>
       		  	<a id="addToCart" href="<?php echo $this->Url(
                            array(
                            'controller' =>  'items',
                            'action'     =>  'addtocart',
                            'id'         =>   $piDetail['id'],
                            )); ?>">Add to Cart</a>
         <?php endif; ?>



<?php endif; ?>

<?php if($piDetail['auctionOrFixed'] == '1'): ?>
	 <a href="#">Buy Now</a>
<?php endif; ?>


  <?php endforeach; ?>

<div id="categories">                                               <!--categories-->





</div>                                                              <!--categories-->



<div id="content">                                                  <!--content-->

<h2>Sign In</h2>

<div class="signin">                                                <!--signin-->



<p>Back for more fun? Sign in now to buy, bid and sell, or to manage your account.</p>



<a href="#"><div class="signin_button">

</div></a>



<h3>Not Registered Yet?</h3>

<p>Join the millions of people who are already a part of the bids or buys family.</p>



<a href="#"><div class="register_button">

</div></a>



</div>                                                              <!--signin-->



<h4>How It Works</h4>

<div class="works">                                                 <!--works-->

<h3>Lorem Ipsum</h3>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet mi nunc, sed egestas ante. Morbi fringilla, nulla ut pulvinar tempus, purus mauris ultricies justo, id consequat sapien tellus ut eros. In facilisis massa sit amet eros molestie luctus. Maecenas adipiscing enim et enim condimentum sit amet hendrerit ante aliquet.</p><a href="#">More...</a>



</div>                                                              <!--works-->



</div>                                                              <!--content-->





<div id="featured">                                                 <!--featured-->

<h5>Featured</h5>



<div class="video">

<div class="videoimg">

<h6>Featured Today</h6>

</div>

</div>



</div>                                                              <!--featured-->



<div id="featured_slider">                      <!--featured-->

<h7>Deals of the day</h7>



<div id="arrow" class="arrowl">

</div>



<div id="fslider">

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Accosories</span></div>

<div class="ftext1">Price:<span> 5$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Jewlery</span></div>

<div class="ftext1">Price:<span> 10$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Navigation</span></div>

<div class="ftext1">Price:<span> 70$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Phones</span></div>

<div class="ftext1">Price:<span> 59.7$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Sports</span></div>

<div class="ftext1">Price:<span> 15$</span></div>

</div>



</div>

<div id="arrow" class="arrowr">

</div>





</div>                                  <!--featured-->



<div class="social">

<h8>Share This Link: <a href="#">www.abcdefg.com/home</a></h8>

</div>


