<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>

<?php endif; ?>

<div>
<?php 
     
?>   
</div>                                                      
<div class="clear"> 

<h3>Latest Listed Item in this Category</h3> </div>


<div id="categories">                                               <!--categories-->
<h3>More Categories</h3>
<ul>

<?php foreach ($this->items as $item): ?>
 <li><a href=<?php echo $this->url(array(
		'controller'=>'items',
		'action'=>'list',
		'cat'=> $item['CategoryName'])); ?> ><?php echo  $item['CategoryName']?></a></li>

  <?php endforeach; ?>

</ul>

</div>





<div id="product">	


<?php foreach ($this->pitems as $pitem): ?>


<div class="itemlist">
<a href=<?php echo $this->url(array(
		'controller'=>'items',
		'action'=>'item-detail',
		'id'=> $pitem['id'],
		)); ?> ><img src="#"  /></a>
             
<h2><a href=<?php echo $this->url(array(
		'controller'=>'items',
		'action'=>'item-detail',
		'id'=> $pitem['id'],
		)); ?> ><?php echo  $pitem['title']?></a></h2>



<h5> Starting Price: $ <?php echo $pitem['startPrice']; ?></h5>

<!-- or <h3> Buy It now for <span>$ <?php echo $pitem['BuyItNowprice']; ?></h3> -->

</div>

<?php endforeach; ?>
</div>




               
               
               
               
               
               

<div class="social">

<h8>Share This Link: <a href="#">www.abcdefg.com/home</a></h8>

</div>


