<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
<h2>Welcome to home</h2>
<?php endif; ?>

<div>
<?php 
     
?>   
</div>                                                      



<?php foreach ($this->pitems as $pitem): ?>


<div id="product">													<!--product-->



<div class="productimg">

</div>



<div class="productviews">

<ul>

<li></li>

<li></li>

</ul>

</div>



<div class="productdesc">

<h15>

		<a href=<?php echo $this->url(array(
		'controller'=>'items',
		'action'=>'item-detail',
		'id'=> $pitem['id'],
		)); ?> ><?php echo  $pitem['title']?></a>
        
        </h15>

<h16>Model Number</h16>

<a href="#"><div class="star">

</div></a>

<h17>Last Price: $8,000.00</h17>

<h17>Price: <span>$5,295.97</span></h17><a href="#">Click here for shipping details</a>

<h17>You Save: $2.704.03</h17>

</div>



</div>



<?php endforeach; ?>



<div class="social">

<h8>Share This Link: <a href="#">www.abcdefg.com/home</a></h8>

</div>


