<h10>REGISTER WITH DIS OR BUYS</h10>
<div class="register">


<p1>Get started and create your personal account,  or <a href="#">start a BidsorBuys Buisness account.</a></p1>

<h14>Tell us about yourself! <span> All FIELDS ARE REQUIRED</span></h14>

<?php echo $this->form; ?>

<h14 style="margin-left:10px;">I have read and accepted the <a style="text-decoration:none; color:#0000d7;" href="#">User Agreement</a> and <a style="text-decoration:none; color:#0000d7;" href="#">Privacy Policy</a></h14>

  <div class="regis_button"></div>





</div>





<div class="social">

<h8>Share This Link: <a href="#">www.abcdefg.com/home</a></h8>

</div>

