<div id="search">													<!--search-->

<h10>Welcome to bids and buY! - SIGN IN!</h10>

</div>																<!--search-->

<div id="signin">

<div id="signinbg">

<h11>Sign In to Your Account</h11>

<div class="signin">												<!--signin-->

<table style="margin:53px 0px 10px 65px;">

<tr>



<?php echo $this->signIn; ?>
<div>	
	<?php if(isset($this->SignUpError))
			echo "<div style='color:red'>".$this->SignUpError."</div>";
	 ?>
</div>
<div> <?php if(isset($this->activationError))
		echo "<div style='color:red'>".$this->activationError."</div>";
	?>
</div>


</tr>

</table>







</div>																<!--signin-->



<h4></h4>

<div class="banner">													<!--works-->

<h3></h3>



</div>																<!--works-->





</div>

</div>





