









<div id="search">													<!--search-->

<h10>Welcome to bids and buY! - SIGN IN!</h10>



</div>																<!--search-->




<div id="signin">

<div id="signinbg">

<h11>Sign In to Your Account</h11>

<div class="signin">												<!--signin-->



<?php echo $this->signIn; ?>

<div>	
	<?php if(isset($this->SignUpError))
			echo "<div style='color:red'>".$this->SignUpError."</div>";
	 ?>
</div>


<!-- <tr>

<td><h12>User ID</h12></td>




<td><input type="text" name="uid" /></td>

</tr>

<tr>

<td><h13>Password</h13></td>

<td><input type="password" name="password" /></td>

</tr> -->



<a href="#"><div class="sin_button">

</div></a>



<a href="#"><div class="regis_button">

</div></a>



</div>																<!--signin-->



<h4></h4>

<div class="banner">													<!--works-->

<h3></h3>



</div>																<!--works-->





</div>

</div>
