
<div id="content">	

												<!--content-->
<?php echo $this->form; ?>
<h2>Sign In</h2>
																<!--signin-->

</div>																<!--content-->





<div id="featured">													<!--featured-->

<h5>Featured</h5>



<div class="video">

<div class="videoimg">

<h6>Featured Today</h6>

</div>

</div>



</div>																<!--featured-->



<div id="featured_slider">						<!--featured-->

<h7>Deals of the day</h7>



<div id="arrow" class="arrowl">

</div>



<div id="fslider">

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Accosories</span></div>

<div class="ftext1">Price:<span> 5$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Jewlery</span></div>

<div class="ftext1">Price:<span> 10$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Navigation</span></div>

<div class="ftext1">Price:<span> 70$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Phones</span></div>

<div class="ftext1">Price:<span> 59.7$</span></div>

</div>

<div class="col2">

<div class="fimage"></div>

<div class="ftext1">Category:<span> Sports</span></div>

<div class="ftext1">Price:<span> 15$</span></div>

</div>



</div>

<div id="arrow" class="arrowr">

</div>





</div>									<!--featured-->



<div class="social">

<h8>Share This Link: <a href="#">www.abcdefg.com/home</a></h8>

</div>


